name: CI

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  extension_ci:
    runs-on: ubuntu-latest

    steps:
      - name: Clone Repository
        uses: actions/checkout@v2
        with:
          submodules: "recursive"

      - name: Clone ESP-IDF
        uses: actions/checkout@v2
        with:
          path: esp/idf
          repository: espressif/esp-idf
          submodules: "recursive"

      - name: Setup Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: "12.x"

      - name: Install Node Dependencies
        run: yarn

      - name: Lint Check
        run: yarn lint

      - name: Package open .vsix
        run: yarn packageWithoutDependencies

      - name: Upload no dependencies .vsix File
        uses: actions/upload-artifact@v1
        with:
          name: esp-idf-extension-open.vsix
          path: esp-idf-extension-open.vsix

      - name: Package .vsix
        run: yarn package

      - name: Upload .vsix File
        uses: actions/upload-artifact@v1
        with:
          name: esp-idf-extension.vsix
          path: esp-idf-extension.vsix

      - name: Run test
        uses: ./.github/actions/idf
        id: idftest

      - name: Get the test output
        run: echo "${{ steps.idftest.outputs.result }}" | tee test-result.xml

  ui_test:
    runs-on: ubuntu-latest

    steps:
      - name: Clone Repository
        uses: actions/checkout@v2
        with:
          submodules: "recursive"

      - name: Run ui test
        uses: ./.github/actions/idf
        id: idfuitest
        with:
          run: /ui-entrypoint.sh
      
      - name: Upload log
        uses: actions/upload-artifact@v1
        if: failure()
        with:
          name: test.log
          path: ./test-resources/test.log
      
      - name: Get the test output
        run: echo "${{ steps.idfuitest.outputs.uiresult }}" | tee ui-test-result.log
